
try {
    throw Error("Danger close!Firing in the hole")
} catch (error) {
    console.log(error.message)
}
